# Generated by Django 2.2.6 on 2019-11-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_remove_book_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.Edition'),
        ),
    ]
