# Generated by Django 2.2.6 on 2019-11-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_pizda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizda',
            new_name='Friend',
        ),
    ]
