# Generated by Django 2.2.6 on 2019-11-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20191120_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ManyToManyField(to='p_library.Book')),
                ('friend', models.ManyToManyField(to='p_library.Friend')),
            ],
        ),
    ]
