# Generated by Django 2.2.6 on 2019-11-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_rentbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentbooks',
            name='book',
        ),
        migrations.AddField(
            model_name='rentbooks',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p_library.Book'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rentbooks',
            name='friend',
        ),
        migrations.AddField(
            model_name='rentbooks',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend'),
            preserve_default=False,
        ),
    ]
