# Generated by Django 2.2.4 on 2019-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0012_auto_20191123_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='logo',
            field=models.TextField(default=''),
        ),
    ]
